merge with develop

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -3,51 +3,121 @@ name: CI/CD Pipeline
 on:
   push:
     branches:
-      - 'main'
-      - 'develop'
-      - 'angular-*'
-    tags:
-      - '2.*'
-      - '3.*'
-      - '4.*'
       - '*'
   pull_request:
     branches:
-      - 'main'
-      - 'develop'
-      - 'angular-*'
+      - angular-19
+      - develop
+      - main
 
 permissions:
   contents: write
-  packages: write
+  id-token: write
+  pages: write
 
-env:
-  REPO_NAME: ${{ github.event.repository.name }}
+#jobs:
+#  build-package:
+#    runs-on: ubuntu-latest
+#    if: github.event_name != 'pull_request' || github.event.action != 'synchronize'
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v2
+#
+#      - name: Set up Git
+#        run: |
+#          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+#          git config --global user.name "github-actions[bot]"
+#          git checkout ${{ github.ref }}
+#
+#      - name: Check for automated release commit
+#        run: |
+#          if git log -2 --pretty=%B | grep -q "chore(release):"; then
+#            echo "Skipping pipeline for automated release commit."
+#            exit 0
+#          fi
+#
+#      - name: Setup .npmrc
+#        run: |
+#          if [ -z "${{ secrets.GN_GITHUB_TOKEN }}" ]; then
+#            echo "ERROR: GN_GITHUB_TOKEN is not set."
+#            exit 1
+#          fi
+#          echo "@dasdigitalplatform:registry=https://npm.pkg.github.com/" >> .npmrc
+#          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GN_GITHUB_TOKEN }}" >> .npmrc
+#          cat .npmrc
+#
+#      - name: Install dependencies
+#        run: npm install
+#
+#      - name: Check commit message for version bump
+#        id: version_check
+#        run: |
+#          if git log -1 --pretty=%B | grep -Eiq "^(feat|fix|BREAKING CHANGE)"; then
+#            echo "Version bump needed. Running version-release."
+#            npm run version-release
+#            NEW_VERSION=$(node -p "require('./package.json').version")
+#            echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
+#          else
+#            echo "No version bump needed. Keeping the same version."
+#            echo "NEW_VERSION=" >> $GITHUB_ENV  # Set to empty
+#          fi
+#
+#      - name: Update subfolder package.json
+#        run: |
+#          if [ "${{ env.NEW_VERSION }}" ]; then
+#            cd projects/design/dls-global-angular/
+#            CURRENT_VERSION=$(node -p "require('./package.json').version")
+#            if [ "$CURRENT_VERSION" != "${{ env.NEW_VERSION }}" ]; then
+#              echo "Updating subfolder package.json version to ${{ env.NEW_VERSION }}..."
+#              npm version ${{ env.NEW_VERSION }} --no-git-tag-version
+#            else
+#              echo "Subfolder package.json is already up to date. No changes needed."
+#            fi
+#            cd ../../..
+#          fi
+#
+#      - name: Commit and push changes
+#        run: |
+#          # Check if there are changes to commit
+#          if [[ -n $(git status --porcelain) ]]; then
+#            git add projects/design/dls-global-angular/package.json
+#            git commit -m "[skip ci] Sync version to ${{ env.NEW_VERSION }}"
+#            git remote set-url origin "https://oauth2:${{ secrets.GN_GITHUB_TOKEN }}@github.com/dasdigitalplatform/dls-global-angular.git"
+#            git push --follow-tags origin HEAD:refs/heads/main
+#          else
+#            echo "No changes to commit."
+#          fi
+#
+#
+#      - name: Build the library
+#        run: npm run release
+#
+#      - name: Upload artifacts
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: dist
+#          path: dist
 
 jobs:
   build-package:
     runs-on: ubuntu-latest
     if: github.event_name != 'pull_request' || github.event.action != 'synchronize'
-    outputs:
-      version_bumped: ${{ steps.version_logic.outputs.version_bumped }}
     permissions:
-      contents: write # Allow the workflow to write to the repository
-      packages: write # Allow the workflow to publish packages
+      contents: write # <--- Add this line to grant write permission for this job
+      packages: write # Keep this for package publishing
     steps:
       - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-          token: ${{ secrets.GN_GITHUB_TOKEN }}
+        uses: actions/checkout@v2
 
       - name: Set up Git
         run: |
           git config --global user.email "github-actions[bot]@users.noreply.github.com" # Best practice for automated commits
           git config --global user.name "github-actions[bot]"                       # Best practice for automated commits
+          git checkout ${{ github.ref }}
 
       - name: Check for automated release commit
         run: |
-          if git log -1 --pretty=%B | grep -Eq "(chore\(release\):|^\[skip ci\]|\[skip ci\]$)"; then
+          if git log -2 --pretty=%B | grep -q "chore(release):"; then
             echo "Skipping pipeline for automated release commit."
             exit 0
           fi
@@ -95,7 +165,7 @@ jobs:
           fi
 
           echo "Pushing all committed changes and tags..."
-          git push --follow-tags origin HEAD
+          git push --follow-tags origin HEAD:${{ github.ref }}
 
       - name: Build the library
         run: npm run release
@@ -106,62 +176,57 @@ jobs:
           name: dist
           path: dist
 
-  build-storybook:
-    runs-on: ubuntu-latest
-    needs: build-package
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Set up Git
-        run: |
-          git config --global user.email "dasdesignsystem@boeing.com"
-          git config --global user.name "dasdesignsystem"
-
-      - name: Check for automated release commit
-        run: |
-          if git log -1 --pretty=%B | grep -Eq "(chore\(release\):|^\[skip ci\]|\[skip ci\]$)"; then
-            echo "Skipping pipeline for automated release commit."
-            exit 0
-          fi
-
-      - name: Setup .npmrc
-        run: |
-          echo "@dasdigitalplatform:registry=https://${{ vars.NPM_REGISTRY_URL }}/" >> .npmrc
-          echo "//${{ vars.NPM_REGISTRY_URL }}/:_authToken=${{ secrets.GN_GITHUB_TOKEN }}" >> .npmrc
-          cat .npmrc
-
-      - name: Clear npm cache and install dependencies
-        run: |
-          npm cache clean --force
-          rm -rf node_modules package-lock.json
-          npm install --loglevel verbose
-
-      - name: Build Storybook
-        run: |
-          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
-            # For main branch, build to public directory (root of GitHub Pages)
-            npm run build-storybook -- --output-dir public
-          else
-            # Extract branch name from refs/heads/branch-name
-            BRANCH_NAME=${GITHUB_REF#refs/heads/}
-            # Create directory with branch name
-            mkdir -p public/$BRANCH_NAME
-            npm run build-storybook -- --output-dir public/$BRANCH_NAME
-          fi
-
-      - name: Upload Storybook artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: storybook
-          path: |
-            public
-            storybook
+#  build-storybook:
+#    runs-on: ubuntu-latest
+#    needs: build-package
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v2
+#
+#      - name: Set up Git
+#        run: |
+#          git config --global user.email "dasdesignsystem@boeing.com"
+#          git config --global user.name "dasdesignsystem"
+#          git checkout ${{ github.ref }}
+#
+#      - name: Check for automated release commit
+#        run: |
+#          if git log -1 --pretty=%B | grep -q "chore(release):"; then
+#            echo "Skipping pipeline for automated release commit."
+#            exit 0
+#          fi
+#
+#      - name: Setup .npmrc
+#        run: |
+#          echo "@dasdigitalplatform:registry=https://${{ vars.NPM_REGISTRY_URL }}/" >> .npmrc
+#          echo "//${{ vars.NPM_REGISTRY_URL }}/:_authToken=${{ secrets.GN_GITHUB_TOKEN }}" >> .npmrc
+#          cat .npmrc
+#
+#      - name: Clear npm cache and install dependencies
+#        run: |
+#          npm cache clean --force
+#          rm -rf node_modules package-lock.json
+#          npm install --loglevel verbose
+#
+#      - name: Build Storybook
+#        run: |
+#          if [ "${{ github.ref }}" != "refs/heads/main" ]; then
+#            npm run build-storybook -- --output-dir storybook
+#          else
+#            npm run build-storybook -- --output-dir public
+#          fi
+#
+#      - name: Upload Storybook artifacts
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: github-pages
+#          path: |
+#            ./storybook/*
+#            public
 
   publish-npm:
     runs-on: ubuntu-latest
     needs: build-package
-    if: needs.build-package.outputs.version_bumped == 'true'
     steps:
       - name: Download build artifacts
         uses: actions/download-artifact@v4
@@ -169,7 +234,7 @@ jobs:
           name: dist
           path: ./dist
 
-      - name: Publish NPM package with dist-tag
+      - name: Publish NPM package
         run: |
           cd dist/design/dls-global-angular
           echo "@dasdigitalplatform:registry=https://${{ vars.NPM_REGISTRY_URL }}/" >> .npmrc
@@ -178,51 +243,62 @@ jobs:
           NPM_PACKAGE_VERSION=$(node -p "require('./package.json').version")
           echo "NPM_PACKAGE_NAME=$NPM_PACKAGE_NAME" >> $GITHUB_ENV
           echo "NPM_PACKAGE_VERSION=$NPM_PACKAGE_VERSION" >> $GITHUB_ENV
-          TAG_NAME="${NPM_PACKAGE_VERSION}"
-
-          # Determine dist-tag based on tag pattern
-          if [[ "$TAG_NAME" == 2.* ]]; then
-            DIST_TAG="angular-18"
-          elif [[ "$TAG_NAME" == 3.* ]]; then
-            DIST_TAG="latest"
-          elif [[ "$TAG_NAME" == 4.* ]]; then
-            DIST_TAG="angular-20"
+          if [[ "$(npm view ${NPM_PACKAGE_NAME} versions)" != *"'${NPM_PACKAGE_VERSION}'"* ]]; then
+            npm publish
+            echo "Successfully published version ${NPM_PACKAGE_VERSION} of ${NPM_PACKAGE_NAME}."
           else
-            DIST_TAG="next"
+            echo "Version ${NPM_PACKAGE_VERSION} of ${NPM_PACKAGE_NAME} has already been published."
           fi
 
-          echo "Publishing ${NPM_PACKAGE_NAME}@${NPM_PACKAGE_VERSION} with dist-tag '$DIST_TAG'..."
-          npm publish --tag $DIST_TAG
 
+#  deploy-storybook:
+#    environment:
+#      name: github-pages
+#      # url: ${{ steps.build-publish.outputs.page_url }}
+#    runs-on: ubuntu-latest
+#    steps:
+#      - id: build-publish
+#        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
+#        with:
+#          path: build # change to your build folder
+#          install_command: npm install
+#          build_command: yarn run build-storybook
 
   deploy-storybook:
     runs-on: ubuntu-latest
-    needs: build-storybook
-    permissions:
-      contents: write
+    env:
+      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
+    environment:
+      name: github-pages
+      url: ${{ github.pages_url }}
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Download Storybook artifacts
-        uses: actions/download-artifact@v4
+      # Manual Checkout
+      - uses: actions/checkout@v4
         with:
-          name: storybook
+          fetch-depth: 0
+      # Set up Node
+      - uses: actions/setup-node@v4
+        with:
+          node-version: '20'
+      #👇 Add Storybook build and deploy to GitHub Pages as a step in the workflow
+      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
+        with:
+          install_command: |
+            echo "@dasdigitalplatform:registry=https://${{ vars.NPM_REGISTRY_URL }}/" >> .npmrc
+            echo "//${{ vars.NPM_REGISTRY_URL }}/:_authToken=${{ secrets.GN_GITHUB_TOKEN }}" >> .npmrc
+            cat .npmrc
+            npm i
+          build_command: npm run build-storybook -- --output-dir public
           path: public
+          checkout: false
 
-      - name: Deploy Storybook to GitHub Pages
-        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8
-        with:
-          folder: public
-          branch: gh-pages
-          clean: true # Automatically clean up old files
 
   pr-develop:
     runs-on: ubuntu-latest
     if: github.event_name == 'pull_request'
     steps:
       - name: Checkout code
-        uses: actions/checkout@v4
+        uses: actions/checkout@v2
 
       - name: Setup .npmrc
         run: |
